---
apiVersion: v1
kind: Service
metadata:
  name: server-internal
spec:
  type: NodePort
  selector:
    app: server
  ports:
    - name: http
      port: 8080
      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      imagePullSecrets:
        - name: acr-auth
      containers:
        - name: server
          image: cotbregistry.azurecr.io/server:latest
          env:
            - name: PORT
              value: "8080"
            - name: GMG_GRILL_HOST
              value: "emulator"
            - name: GMG_STATUS_POLLING_INTERVAL
              value: "2000"
          ports:
            - containerPort: 8080


---
apiVersion: v1
kind: Service
metadata:
  name: emulator
spec:
  type: NodePort
  selector:
    app: emulator
  ports:
    - name: gmg
      protocol: UDP
      port: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emulator
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: emulator
  template:
    metadata:
      labels:
        app: emulator
    spec:
      imagePullSecrets:
        - name: acr-auth
      containers:
        - name: emulator
          image: cotbregistry.azurecr.io/emulator:latest
          ports:
            - containerPort: 8080

            
