---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  loadBalancerIP: 23.96.36.10
  type: LoadBalancer
  selector:
    app: server
  externalTrafficPolicy: Local
  ports:
    -
      name: http
      port: 80
      targetPort: 8080